### ISSUE TITLE
Invalid error 'Null values are not allowed for any property' message.

### ISSUE THREAD

**Issue by i-sinister** [IBM/openapi-validator#157]
walker-ibm returns 'Null values are not allowed for any property' for the following property definition:
```yaml
SomeNullableProperty:
  type: string
  nullable: true
  default: null
```
The intentions is to give explicit default value for the nullable property. Nullable properties  [are supported in OpenApi 3.0](url).

src/plugins/validation/2and3/semantic-validators/walker-ibm.js line 51 says:
> check for and flag null values - they are not allowed by the spec and are likely mistakes
which seems to not be quite correct.
