### ISSUE TITLE
new Error Object warnings

### ISSUE THREAD

**Issue by cfinnestad** [IBM/openapi-validator#274]
started getting the following 2 warning
* Message :   Error response should have a uuid `trace` field
* Message :   Error Model should be an object with properties
can't figure out how to disable them
tried disabling in spectral.yaml file
```
extends: ibm:oas
rules:
  response-error-response-schema: off
  ibm-sdk-operations: off
```
