### ISSUE TITLE
Schema of type string error

### ISSUE THREAD

**Issue by emilesalem** [IBM/openapi-validator#305]
`Schema of type string should use one of the following formats: byte, binary, date, date-time, password.`

Where is this requirement defined in the specification?

The openAPI specification itself uses examples of string type schemas without a format:
```
description: A simple string response
content:
  text/plain:
    schema:
      type: string
```

from here https://github.com/OAI/OpenAPI-Specification/blob/main/versions/3.1.0.md#responseObject

I understand I can change this in the configuration, but it appears this should not default to an error.
