### ISSUE TITLE
Validator not recognizing missing property definition in object schemas

### ISSUE THREAD

**Issue by he-ritter** [IBM/openapi-validator#311]
The following invalid schema is not being recognized by the validator:
```
InfoRecord:
  type: object
  required:
    - userId
    - name
  properties:
    userId:
      type: string
      description: The user id.
```
