### ISSUE TITLE
"localhost" is not considered a valid host for "openIdConnectUrl"

### ISSUE THREAD

**Issue by JenswBE** [IBM/openapi-validator#338]
# Problem

Linter doesn't like `localhost` in `openIdConnectUrl`

```yaml
# File: openapi.yml
  securitySchemes:
    localAuth:
      type: openIdConnect
      openIdConnectUrl: http://localhost:9001/auth/realms/go-commerce/.well-known/openid-configuration
```
```
  Message :   openIdConnectUrl must be defined for openIdConnect property and must be a valid URL
  Rule    :   builtin
  Path    :   securitySchemes.localAuth
  Line    :   0
```

# Workaround

A simple workaround is to use `127.0.0.1` instead.

# Possible solutions

After some digging in the source code, I see you're using the helper `isURL` from package `validate` to check this url: https://github.com/IBM/openapi-validator/blob/main/src/plugins/validation/oas3/semantic-validators/security-definitions-ibm.js#L168

I see 2 solutions to this issue:
1. Use option `{ host_whitelist: ['localhost'] }` as second argument to `isURL`. This seems the cleanest solution to me. Unfortunately, there is a related [issue](https://github.com/validatorjs/validator.js/issues/1731) and [PR](https://github.com/validatorjs/validator.js/pull/1748). The fix is not yet merged on the latest release, but the option could already be provided. Therefore, the issue will be automatically solved when the version of `validate` can be bumped.
2. Use option `{ require_tld: false }` as second argument to `isURL`. This will immediately solve the issue, but also allow non fully qualified domain names. Depending on how strict you want the check to be, this might be a show stopper.
