### ISSUE TITLE
`string-boundary` check doesn't appear to include `path` parameters

### ISSUE THREAD

**Issue by meem** [IBM/openapi-validator#352]
Our API includes many parameters such as:

```
  parameters:
    snapshotId:
      name: snapshot_id
      in: path
      description: |-
        The snapshot identifier
      required: true
      schema:
        type: string
```

(Note the use of `type: string` without any `minLength`, `maxLength`, or `pattern` qualifiers)

However, these do not appear to included in the validator's `string-boundary` check, while `query` parameters are (correctly)  checked.
