### ISSUE TITLE
Trouble disabling request-body-object (2)

### ISSUE THREAD

**Issue by vmarkovtsev** [IBM/openapi-validator#366]
The following `.spectral.yml` no longer disables `request-body-object` rule in 0.53.1. The same file worked well in 0.52.2.
```yaml
extends: '@ibm-cloud/openapi-ruleset'
rules:
  request-body-object: off
```
