### ISSUE TITLE
Please output spectral configuration validation errors to console

### ISSUE THREAD

**Issue by Havunen** [IBM/openapi-validator#379]
It is currently very difficult to adjust configurations between openapi validator versions, because errors are not shown to console.

Have spectral file like this:

```
extends: '@ibm-cloud/openapi-ruleset'
formats: ["oas3"]
rules:
  request-body-object: 'off'
  content-entry-provided:
    description: non-204/404 responses should define a content object
    given:
      - "$.paths[*][*].responses[?(@property != '204' && @property != '404')]"
    severity: error
    resolved: true
    then:
      field: content
      function: truthy
  response-example-provided: 'off'
  string-boundary: 'off'
  prohibit-summary-sentence-style: 'off'
  description-mentions-json: 'off'
  schema-description: 'off'
  property-case-convention:
    description: Property names must follow a camel case naming convention
    given: schemas
    severity: error
    resolved: true
    then:
      function: propertyCaseConvention
      functionOptions:
        type: camel

```

and use open api validator through code ( something like this):

```
import ibmValidator from 'ibm-openapi-validator';

    ibmValidator(openAPiSchema)
        .then((validationResults) => {
                 for (const err of validationResults.errors) { 
                      console.log(err);
                 }
        });

```

all validation errors are ignored because "debug" parameter is undefined in spectra-validator.js  checkGetRulesetError and then it silently fallsback to ibm open api default config and causes a lot unrelated errors
