### ISSUE TITLE
securityScheme import:  Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by apestov** [IBM/openapi-validator#39]
##### VERSION
ibm-openapi-validator: 0.5.0

##### SUMMARY
Validator fails with ` Cannot read property 'toLowerCase' of undefined`  on securityScheme import like:
```
components:
  securitySchemes:
    securitySchemaN1:
      $ref: 'base.yaml#/components/securitySchemes/securitySchemaN1'
```

##### STACK TRACE
```
TypeError: Cannot read property 'toLowerCase' of undefined
    at each (C:\example\node_modules\ibm-openapi-validator\src\plugins\validation\2and3\semantic-validators\security-definitions-ibm.js:31:21)
    at C:\example\node_modules\lodash\_createBaseFor.js:17:11
    at baseForOwn (C:\example\node_modules\lodash\_baseForOwn.js:13:20)
    at C:\example\node_modules\lodash\_createBaseEach.js:17:14
    at forEach (C:\example\node_modules\lodash\forEach.js:38:10)
    at Object.module.exports.validate (C:\example\node_modules\ibm-openapi-validator\src\plugins\validation\2and3\semantic-validators\security-definitions-ibm.js:23:3)
    at Object.keys.forEach.key (C:\example\node_modules\ibm-openapi-validator\src\cli-validator\utils\validator.js:70:40)
    at Array.forEach (<anonymous>)
    at validateSwagger (C:\example\node_modules\ibm-openapi-validator\src\cli-validator\utils\validator.js:69:30)
    at processInput (C:\example\node_modules\ibm-openapi-validator\src\cli-validator\runValidator.js:211:17)
```

##### STEPS TO REPRODUCE
1. Create `base.yaml`
```
components:
  securitySchemes:
    securitySchemaN1:
      description: example description
      type: apiKey
      in: cookie
      name: userAuthCookie
```

2. Create `main.yaml`
```
openapi: 3.0.0

paths: {}

components:

  securitySchemes:
    securitySchemaN1:
      $ref: 'base.yaml#/components/securitySchemes/securitySchemaN1'
```

3. Launch validator
```
$ lint-openapi main.yaml
[Warning] No .validaterc file found. The validator will run in default mode.
To configure the validator, create a .validaterc file.

[Error] There was a problem with a validator.
Cannot read property 'toLowerCase' of undefined
```

##### Expected result
ibm-openapi-validator will use the securityScheme definition inside main.yml without `Error`.

#### References

Per [openapi 3.0 specification schema](https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml) the `securitySchemes` items can be a reference:

```
      securitySchemes:
        type: object
        patternProperties:
          '^[a-zA-Z0-9\.\-_]+$':
            oneOf:
              - $ref: '#/definitions/Reference'
              - $ref: '#/definitions/SecurityScheme'
```
