### ISSUE TITLE
BUG: 'Enum values must be snake case' on enums like '400', '500'

### ISSUE THREAD

**Issue by MaxProfit** [IBM/openapi-validator#667]
version: 1.18.0

```
IBM OpenAPI Validator (validator: 1.18.0), @Copyright IBM Corporation 2017, 2024.

Validation Results for api/openapi.yaml:

Errors:

  Message :   Enum values must be snake case
  Rule    :   ibm-enum-casing-convention
  Path    :   components.schemas.ErrorInner.properties.code.enum.0
  Line    :   413

  Message :   Enum values must be snake case
  Rule    :   ibm-enum-casing-convention
  Path    :   components.schemas.ErrorInner.properties.code.enum.1
  Line    :   414
```

The lines in question:

```
    ErrorInner:
      properties:
        message:
          type: string
        code:
          description: The HTTP status code
          type: string
          enum:
            - '400'
            - '500'
        more_info:
          type: string
```

I'm following the way the validator is telling me to do HTTP errors and then I get this error saying I need to do snake case on number strings? Weird since there are literally no word characters there?

Spectral and Redocly have no issues with my openapi.yaml, as a reference.

**Comment by dpopp07** [comment]
I think the root of the issue is the fact that the "code" value is not meant to be the HTTP 
status code, which is intended to be captured at the error container level, rather than the error model level. See our [API Handbook](https://cloud.ibm.com/docs/api-handbook?topic=api-handbook-errors#error-model) for more info. The documentation for the "code" value says:

> This field MUST contain a snake case string succinctly identifying the problem.

We could ostensibly rethink if we want to allow numbers at the beginning of a valid snake-case string but in this case, I think we're actually seeing intended behavior.

**Comment by MaxProfit** [comment]
You're certainly correct that I wasn't doing it right for the error type. I've corrected that now, thanks!

I made another enum in a different place and the values still couldn't be represented as strings representing integers though, from what I know about the spec it allows this, so this is still a bug?

```
components:
  schemas:
    TestSchema:
      type: string
      enum:
        - '400'
        - '500'
```

```
IBM OpenAPI Validator (validator: 1.18.0), @Copyright IBM Corporation 2017, 2024.

Validation Results for api/openapi.yaml:

Errors:

  Message :   Enum values must be snake case
  Rule    :   ibm-enum-casing-convention
  Path    :   components.schemas.TestSchema.enum.0
  Line    :   256

  Message :   Enum values must be snake case
  Rule    :   ibm-enum-casing-convention
  Path    :   components.schemas.TestSchema.enum.1
  Line    :   257
```
