### ISSUE TITLE
Rule "ibm-required-array-properties-in-response" throws errors for schemas with 'allOf' keyword

### ISSUE THREAD

**Issue by emlaver** [IBM/openapi-validator#690]
We are seeing several errors for this rule, and each error references a schema that already contains the field in the `required` list.  
I'll use the below schema `SchedulerJobsResult` as an example:
```
---
additionalProperties: false
allOf:
  - $ref: "../../index.yaml#/components/schemas/CommonViewResult"
  - additionalProperties: false
    properties:
      jobs:
        description: "Array of replication job objects."
        items:
          $ref: "../../index.yaml#/components/schemas/SchedulerJob"
        maxItems: 4294967296
        minItems: 0
        type: "array"
    type: "object"
required:
  - "jobs"
  - "offset"
  - "total_rows"
description: "Schema for a listing of replication scheduler jobs."

```
It throws the error:
```
  Message :   In a response body, an array field MUST NOT be optional
  Rule    :   ibm-required-array-properties-in-response
  Path    :   components.schemas.SchedulerJobsResult.allOf.1.properties.jobs
```

If I remove the `allOf` and just have one set of properties, I don't see the error.

This was tested with `ibm-openapi-validator` version `1.25.0`.
