### ISSUE TITLE
const keyword is disallowed in 3.1

### ISSUE THREAD

**Issue by Georgegriff** [IBM/openapi-validator#736]
```
  Message :   Found disallowed keyword: const
  Rule    :   ibm-schema-keywords
  Path    :   components.schemas.AccountResponse.properties.type.const
  Line    :   85

```

```
      properties:
        type:
          type: string
          const: account
```

It is my understanding that openapi 3.1 should support all of the fields of json schema spec, so this should be valid?
